### ISSUE TITLE
Having a global variable named __appRoot or similar might simplify imports. 

### ISSUE THREAD

**Issue by justchen1369** [Team-G4/g4-next#1]

**Comment by scintilla4evr** [comment]
you mean those?
![image](https://user-images.githubusercontent.com/11379882/71770973-47585e80-2f34-11ea-9d04-3706e653bc34.png)

**Comment by justchen1369** [comment]
Yes: in vanilla js I would do 
```js
global.__appRoot = __dirname
```
In the `index` file.

**Comment by scintilla4evr** [comment]
But why, since:
a) the imports are like this because of the directory structure
b) this is TypeScript only, the vanilla JS is generated by `tsc`

**Comment by scintilla4evr** [comment]
Yes, those would be simplified, but other ones would become needlessly long, like "./cannon" referring to the cannon.ts file in the same dir

**Comment by justchen1369** [comment]
Yeah, good point. And now that I think of it, moving around directories would break less stuff with relative paths.
